name: plugin_sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  modal_bottom_sheet:
    path: plugins/modal_bottom_sheet
  raminfo:
    git:
      url: https://github.com/akadatsky/raminfo
      ref: master
  cupertino_icons: ^1.0.2
  slider_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true